---
- name: download confd
  get_url:
    url="{{confd_download}}"
    dest="{{confd_home}}/confd"
    mode=0755

- name: create confd config directories
  file:
    state=directory
    path="{{item}}"
  with_items:
  - "{{confd_config}}/conf.d"
  - "{{confd_config}}/templates"

- name: create template resource configs
  template:
    src=resource.toml.j2
    dest="{{confd_config}}/conf.d/{{item.resource_name|default(item.service_name + '.toml')}}"
  with_items: confd_resources

- name: create template configs
  copy:
    src="{{item.template}}"
    dest="{{confd_config}}/templates/{{item.template_name|default(item.service_name + '.conf.tmpl')}}"
  with_items: confd_resources

- name: add cron task
  cron:
    name='confd sync'
    job="confd -onetime -backend {{confd_backend}} {% for node in confd_backend_nodes %} -node {{node}} {% endfor %} >> /var/log/confd-sync.log 2>> /var/log/confd-sync.err"
    minute='*/1'
    state=present
