---
- name: download confd
  get_url:
    url="{{confd_download_url}}"
    dest="{{confd_binary_path}}"
    mode=0755

- name: create confd config directories
  file:
    state=directory
    path="{{item}}"
  with_items:
  - "{{confd_config_directory}}/conf.d"
  - "{{confd_config_directory}}/templates"

- name: create template resource configs
  template:
    src=resource.toml.j2
    dest="{{confd_config_directory}}/conf.d/{{item.resource_name|default(item.service_name + '.toml')}}"
  with_items: confd_resources

- name: create template configs
  copy:
    src="{{item.template}}"
    dest="{{confd_config_directory}}/templates/{{item.template_name|default(item.service_name + '.conf.tmpl')}}"
  with_items: confd_resources

- name: run confd
  shell: '{{confd_cmd}}'

- name: add cron task
  cron:
    name='confd sync'
    job="{{confd_cmd}} >> /var/log/confd-sync.log 2>> /var/log/confd-sync.err"
    minute='*/1'
    state=present
